---
namespace: mssql
stack:
  defines: process-group
  runnable-list:
    - mssql/mssql
  variables:
    mssql_password:
      type: string
      value: P@ssw0rd
    mssql_port:
      type: int
      value: 1433
